ci: add check final new line

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,3 +46,25 @@ jobs:
       - uses: actions/checkout@v4
       - name: REUSE Compliance Check
         uses: fsfe/reuse-action@v4
+        
+  final_newline_lint:
+    runs-on: ubuntu-latest
+    name: Check final newline
+    steps:
+      - name: Install ripgrep
+        run: sudo apt-get install -y ripgrep
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Check final newline is present
+        run: |
+          # search missing final newline
+          if rg -Ul '[^\n]\z' -g '!*.svg' .; then
+            echo "Found missing final newline on listed file(s)"
+            exit 1
+          fi
+
+          # search multiple final newlines
+          if rg -Ul '\n\n\z' .; then
+            echo "Found multiple final newlines on listed file(s)"
+            exit 1
+          fi
